"""Add new fields to models

Revision ID: 02bf5fd0245c
Revises: b5206f05aeee
Create Date: 2025-08-05 17:57:52.561339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bf5fd0245c'
down_revision = 'b5206f05aeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriber_email'), ['email'], unique=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_status'))
        batch_op.drop_index(batch_op.f('ix_post_published_at'))
        batch_op.drop_column('published_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_email'))

    op.drop_table('subscriber')
    # ### end Alembic commands ###
